# DB
SCHEMA = "dudu_fidelidade"

# CPF_validation
FIRST_DIGIT_POSITION = 9
SECOND_DIGIT_POSITION = 10
FIRST_DIGIT_MULTIPLIER = 11
SECOND_DIGIT_MULTIPLIER = 12
MULTIPLIER = 10
DIVIDER = 11
CPF_LENGHT = 11
